#!/usr/bin/env bash
# This script displays messages when receiving signals

pidfile="/var/run/myscript.pid"

# Function to clean up and exit
cleanup() {
    echo "Cleaning up and exiting"
    rm -f "$pidfile"
    exit
}

# Create a PID file
echo $$ > "$pidfile"

# Trap signals
trap 'echo "I hate the Kill command"; cleanup' SIGTERM
trap 'echo "Y U no love me?!"; cleanup' SIGINT
trap 'cleanup' SIGQUIT

while :
do
    echo "To infinity and beyond"
    sleep 2
done
